[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "7573fd8cb3cd69e26208ccce9d01d4df5a66d45c"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "d3d4c4384a2b734104e72bd84b2d4d526f791c9f947dfe07b1a177867b85ff47"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.aarch64-apple-darwin.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "3949eee0f06637fe81ba4458bf4a0d2b3ad8cb24"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "d55946c1461377c8efd982a1a5718cf5a37cedb3d0fb7a29c84a727eefb55f9c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.aarch64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "0b5d36b7ae103d6c8aef21033863e8a3fd0179e4"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "5f03d7bb5a5344f6d9469045358cff700adfa03f8921481175b1f534bf7c8d2c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.aarch64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "19cc3c4f0782cb23e9a979cb33ca77dd4cd1dfdf"
os = "freebsd"

    [[SuiteSparse32.download]]
    sha256 = "a45f37550d8692c468d096a40b520e111f88b52acaa6276962971d59807f8b3e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.aarch64-unknown-freebsd.tar.gz"
[[SuiteSparse32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8365f24a3c7c0be9e7956997bd200c5398a4015"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "a79a7742c6a33a08dbf0ccf0b916ae63cafcd843a4d04f26b703516ef658eb89"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea79b60e73c76a651a3f36b217089aaae7d23edf"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "f804efc6f4bcf4bd375e02cac967efe20c0ca1948daa51572ce536aee2f60edc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bdf476ff650f9d047f64001bf0b48bb366d3a87"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "f9ec629bb1160b3505a1910721b14c98d5b1bc469233521038be8ff271cc7783"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b25e9231f7a7c6a29636c36922ee0cd2d8295b2"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "5c55a1b9a1816b5b18d06043b0e803ad3108d4949fd1e520e728adf57ae06fc2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "ea3b0d07f6d7a55cac487d50d073994029a6fbe4"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "2908fe4a5d2194eeea61b0e509e7e3bfe6dbdfcacfe8734723ca13abe694a5f2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.i686-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "c55392ebc9a5f2e2d6859d49a1b80b6dc80092f7"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "4f8fe082243e902858ef984e0338cbc4ed5e382629212a042752679c0d0d395d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.i686-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "3ffced04acaf446aa11f56243028ac98ca689dc9"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "37a569e93e2a58b49659acf6fa5e24d290fad6dd95afe86a6a484189c4a54be5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.i686-w64-mingw32.tar.gz"
[[SuiteSparse32]]
arch = "powerpc64le"
git-tree-sha1 = "97dce586fddb1d16fa0c22bcb90bff809a9a6fd0"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "b843ceab64da751d39a613fde27e8143e31cd30ff1c2e7184f9163e1656f70e2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "riscv64"
git-tree-sha1 = "fa87db98bc380f92131287ae844570ff33a60e03"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "1d93757af521cb20bbf9de35fef49229412f8320ff80c5e54b887574473bd85d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.riscv64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "4c9d30f825af7b8072e6543bf6841409525fe373"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "a1a7fc3829a3f26327278a1af0a8817c43f6fa54cb3a2301ddcc709afe8dcc25"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.x86_64-apple-darwin.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "65dd4e79b34c55182e477b70d6786a24a62dc49f"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "d0d05ac82e5171b21abb4d49facdeb01d1c7e730d2a8f3314c6fb30af33b18c0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.x86_64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "7c28cbe2c4ae5be328073a606f1dd11cc96720e2"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "1a2788b1c3466b52a3e8bca193a06a8b48c7fcc01723a65f05e5fc6c291196fe"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.x86_64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "6a247c3a2af7ede8808e856431c61324bd2ed515"
os = "freebsd"

    [[SuiteSparse32.download]]
    sha256 = "5473f2c3b8c1e6293f688391081b089b318368f900ac917e75241c8c532f6623"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "e3eacf2b70ca9498f07ce92009e85653177c95ee"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "5c4fb48d2ad397e50f1da2ec4012d9b882e2213072bbd5ac34ce8e93ca98d218"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v7.8.3+0/SuiteSparse32.v7.8.3.x86_64-w64-mingw32.tar.gz"
