[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "f8329608605ede3afee8bbe4b62b55a083648fcd"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "91bac555dcf3b05ae09fbbff358e0ae98993ff35c6f94b7be8163efbf7763528"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "bbb33eb4e19efd735e9f0cbff70c1c46c7374f50"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "a16810d8ede38c9d43a261ac503051c769e6591a91f52e6728b5e180534a40d7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e9f81a4478bbc8477201a33b65495d4749bf2f7"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "5c0846760d762c2de0ed28dee50c0fd2f5e9a32f54e1bff17d3dddc973870a31"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "247edf60133dbb18508a9ceab2911b2cb4a4f5e6"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "2e7239bfcbd0a20f52b6082fd069e952865c24b7bb723252f2c53d3441580d99"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "a6b5ac332a1d6d53809382e70c37a66322c66384"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "e8897be29d63be686a6ec85da18c5d08c4e307aa44489b6baae61c5fced22d56"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.i686-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "ffeb897bec58cbbd8293230c2834b5c8c314cc2b"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "80b13d37b27adb813fb0a1468c48f9217c813ff4253f82ce2cdc28109eca1974"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.i686-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "aaa35b995bc727d9b34a2ff71b6fdf4b9651175d"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "cdd43f744643f30b9e0b00be3d0fe35932fa318bde26837f09afc5534415cc29"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse32]]
arch = "powerpc64le"
git-tree-sha1 = "0d0d8bed3f676530c9269b8591a4c2d5fbb14ffe"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "0b7246b1f436ceae689561a861a2a75dc090e71c120c306e73b66ae8a00befb0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "22904105af97c99db50e9a356f074e02842cde0e"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "3e89b2c1723507516b20d63ff895d0e9e4cf13d557892c789779f484968cb03b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "70e6ebfa6d40b049d611d0ed90fe685bf3404edb"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "ed1f4cf852825e35e85fc1d171d9f068bba22aeca5b2277b392a09b67c126acf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "72d59b6ef5682ca9926811e435099bc6eae8a808"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "3194d3a4dc41c9869d54fc48a68fca5c9df3c1dd5b84231a549f7453d232805c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "528fac8e9230f51c224f612681a0cb64408bea5b"
os = "freebsd"

    [[SuiteSparse32.download]]
    sha256 = "8df610f107050ba611242dd50793756e55b7e2721185e2b4e4a2a570ffc41740"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "81b95103c0344e7e8b446f8f4e2db4a8e6930325"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "e9f5c9aec82509aa7012e3fb8e05af02356e08657655e8304fc60a05fd40a213"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.8.1+0/SuiteSparse32.v5.8.1.x86_64-w64-mingw32.tar.gz"
