[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "3b5dadc758e1db59bece4fafdbf7a605dc353416"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "8a3013d990e10a7cb520c50e1b998eebce58581f236a4117473a45cfd1e55b24"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "51ebf466401713ecd25a9a526fd5830ab4ba4c45"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "9ad96f2ee208d9cca2286fb93f3f61aa9fc7f1478d7c2de7c1c776eee57ac0b0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
git-tree-sha1 = "e07e4d3685a8a5221f3cc76a47c46caee256bb4a"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "8489f88db5ecba6411edc1eba3aee6b80d007543bba2f9838aba0d8cf08caf05"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
git-tree-sha1 = "0aaab8d2e6b7487af6294977a59674ed75de9eb6"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "ef2db14c2f12ae46fbccba4971e73e48c8e5fa7fe13a03a1fcf0ca035c56b6f2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "26d17cd5c62152711cd48a2b58a4acd066a7b5f2"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "e776d1ff2efa01d1ef27b04a10445836bff754d1724411649d2e38ddc6fad1ef"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "5bbeb5b9e15cdc98878db958b75a2105643c20b9"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "18ce70c413e83bf14eaae5eeff6c23b8220460097f3e1237d24313fd0d69644f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "b71f810ca7e749c93acfcce8bd9ca9bbda8f1db4"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "1b58f60007843aaa8f34189f6a9f0e6f76065892ad35900b2c5709b8a24cc249"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse32]]
arch = "powerpc64le"
git-tree-sha1 = "9a5835ee0c87462dfbec48ca4ef7d078029c8da1"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "333068f6d885a57d771ac930a14f1b7b0383011c0f1846d50c48c5889308b78b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "f2da02d5dfe707b501c097e6ca2c37890a84b9fd"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "8c7a989d6be0f4363c51faf88b51a78fad742a29c9e50d15381147c7407efd36"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "ba4af23abe52279a354a0faacb1b16dc85e12efe"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "83df4a74177af44f24d936a7842010c31466814630a9156def5280230457421e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "37add154ae8c80c794320b49da44a2f49ff9e252"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "948654f72b828f1929f1ec24d7606a7e984f2bc319a14a75e76fc315325f84b8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "628e10839996a90fe5b9828dfd9f2ce2e1ab2d10"
os = "freebsd"

    [[SuiteSparse32.download]]
    sha256 = "268c43a950d2395d7243caceb058ea7e06dd78f4b6c4f7c903ab37c1331d0cd3"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "5a64140aa0877ee7b5a0c00d6f5416fdce96c73c"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "873844ad70ed88186d0a016d8ea9ff45770493fc356ad7564cf5f0476cae0174"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.4.0+1/SuiteSparse32.v5.4.0.x86_64-w64-mingw32.tar.gz"
