[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "34619846bcdc7f9dd54a3e240d778da25772302c"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "c08d1f5adfb5ddda303488837cc3cf2843b06bb8d071f2e37216d74308367cd4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "192061b8d1eb8ee16f96c5feb1c3c2681ce496e3"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "788670d06918e9b733b83e303e58dca0e744944a82e419687cdd0b0d4ce5664f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "aarch64"
git-tree-sha1 = "9e733089c8c962381850e3c338018ab8cae4fe70"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "4ae858d3fb722aba7fd9eec11479ce1af22d45e19ec628aca4018e9162767d24"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9113fe49043071f0d744ddffddfd6868c8bd6a8"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "f944eb79c036b7a4989b8e95bca8f87a807507ae26e84fefa081e212948f62d9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "039a4586db3cdf2698464a6e7acf47eae58c4c6d"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "8ceda5ccf23bd5926746c61bbe936d9a11095570ab6e1a59ce49c1f07b33ea4e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ed5f59f84c398bcf68a512cf68da436e011ab54"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "33d1ac3b2af6a1e396efe9f1e000103bbe70efdc1bf268b1cadb6055efe80d2c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0ab21a60772bcb29214aa46142b2c9e82749edf"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "e1f8ad87fc25455721c79a6d9cb13a7ab0fcdae79b82b1ad167e7a2a749cdda0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "657122944d7e1e038db64bb62b2c6ab4bb51afc7"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "746632b74b68516b3479a2bf472f19406d6808d163890d057d3ad44783ac7a00"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.i686-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "c4f86e1dc0f62f58190b50ba7cae028ba4c449b6"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "a5c92feb1f721ff6f81703ad502673bd45c5d2a5890d5adc4be67cd6cdaf5a04"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.i686-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "i686"
git-tree-sha1 = "71f1935219ab53822b0e9a1c0fba1cfc29695fff"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "81b4c20f3da9ca388345e1b973f3a198068ffdff402d3b1cbdf156a3884e4379"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse32]]
arch = "powerpc64le"
git-tree-sha1 = "1f7f62fc4198327c64e06b87b292bd1492b6e316"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "2f08c4e311938c74d2112ffafb9ebdf22c06391649726565344a42d0e614b388"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "dffb1ce08c192a7fdeec02bc4664227e429204ad"
os = "macos"

    [[SuiteSparse32.download]]
    sha256 = "212d2d4e800a2cd3fd819837ce056a5714ddee13a6f9a9fc8dc2d8b6978ee6b2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "95b3d45dbbd84d20c148bc04f995134c8ab1d466"
libc = "glibc"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "8e43634dbbf7e485feee3659b71bf39b296d1e1e44039fc2ff390be3612cf5ec"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "1fbb2ae006b73e9c25ef5a4d469fbe9ff8d7e607"
libc = "musl"
os = "linux"

    [[SuiteSparse32.download]]
    sha256 = "852eb9c62b971a0713cec2c965871f6e04193d122fd0362eab919e410874dacf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "c9419ca4932600ab8bf7d5ba1d50b96ebe3a2efd"
os = "freebsd"

    [[SuiteSparse32.download]]
    sha256 = "7a88a344819aa8f59470cd89ded5b6f0af93e932c5691441804f3b331797466b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse32]]
arch = "x86_64"
git-tree-sha1 = "086aa2b286bf590e4700ed76db5a8c4a12b13513"
os = "windows"

    [[SuiteSparse32.download]]
    sha256 = "7054b84f8c0323e752da5baacb289691776f8f457e3dc1c03e68bef071c5a1a2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse32_jll.jl/releases/download/SuiteSparse32-v5.10.1+0/SuiteSparse32.v5.10.1.x86_64-w64-mingw32.tar.gz"
