# Autogenerated wrapper script for SuiteSparse32_jll for x86_64-w64-mingw32
export libamd_a, libbtf_a, libcolamd_a, libklu_a, libsuitesparseconfig_a

JLLWrappers.@generate_wrapper_header("SuiteSparse32")
JLLWrappers.@declare_file_product(libamd_a)
JLLWrappers.@declare_file_product(libbtf_a)
JLLWrappers.@declare_file_product(libcolamd_a)
JLLWrappers.@declare_file_product(libklu_a)
JLLWrappers.@declare_file_product(libsuitesparseconfig_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libamd_a,
        "bin\\libamd.lib",
    )

    JLLWrappers.@init_file_product(
        libbtf_a,
        "bin\\libbtf.lib",
    )

    JLLWrappers.@init_file_product(
        libcolamd_a,
        "bin\\libcolamd.lib",
    )

    JLLWrappers.@init_file_product(
        libklu_a,
        "bin\\libklu.lib",
    )

    JLLWrappers.@init_file_product(
        libsuitesparseconfig_a,
        "bin\\libsuitesparseconfig.lib",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
